export const SETTINGS_KEYS = {
  cleanupAppAssignments: "cleanup_app_assignments",
  cleanupCustomPrompt: "cleanup_custom_prompt",
  cleanupEmailTone: "cleanup_email_tone",
  cleanupIntensity: "cleanup_intensity",
  cleanupOverallTone: "cleanup_overall_tone",
  cleanupPersonalTone: "cleanup_personal_tone",
  cleanupWorkTone: "cleanup_work_tone",
  freestyleCloudPanelExpanded: "freestyle_cloud_panel_expanded",
  hotkey: "hotkey",
  hotkeyMode: "hotkey_mode",
  hotkeyToggle: "hotkey_toggle",
  historyPaused: "history_paused",
  historyRetentionDays: "history_retention_days",
  language: "language",
  llmCleanup: "llm_cleanup",
  localLlmApiKey: "local_llm_api_key",
  localLlmUrl: "local_llm_url",
  micDeviceId: "mic_device_id",
  mlxAsrKeepAliveMinutes: "mlx_asr_keep_alive_minutes",
  networkCaCertPath: "network_ca_cert_path",
  networkProxyUrl: "network_proxy_url",
  outputMode: "output_mode",
  soundEnabled: "sound_enabled",
  theme: "theme",
} as const;

export type SettingsKey = (typeof SETTINGS_KEYS)[keyof typeof SETTINGS_KEYS];
